## The Inverse Matrix 
$A^{-1} = AB = BA$

In [9]:
import numpy as np

# input two matrices of size n x m
A = [[1,2,1],
     [4 ,4,5],
     [6 ,7,7]]

B = [[-7,-7,6],
     [2,1,-1],
     [4,5,-4]]

print (np.array(A), "\n")

print (np.array(B), "\n")

print (np.dot(A,B), "\n")
print (np.dot(B,A), "\n")

[[1 2 1]
 [4 4 5]
 [6 7 7]] 

[[-7 -7  6]
 [ 2  1 -1]
 [ 4  5 -4]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]] 



## Transpose
$A^{T}$

In [10]:
A_t = np.transpose(A)
print (np.array(A), "\n")
print (A_t)

[[1 2 1]
 [4 4 5]
 [6 7 7]] 

[[1 4 6]
 [2 4 7]
 [1 5 7]]
